In [1]:
import numpy as np

In [3]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

# np.sort

In [6]:
np.sort(a,kind='mergesort') # mergesort is fast

array([10, 16, 16, 22, 39, 51, 54, 56, 64, 68, 75, 75, 82, 99, 99])

In [8]:
b

array([[ 9, 91, 68, 59],
       [20, 81, 12, 22],
       [29, 47, 25, 72],
       [57, 61, 15, 84],
       [96, 74, 38, 97],
       [99, 60, 93, 16]])

In [9]:
np.sort(b) # row wise

array([[ 9, 59, 68, 91],
       [12, 20, 22, 81],
       [25, 29, 47, 72],
       [15, 57, 61, 84],
       [38, 74, 96, 97],
       [16, 60, 93, 99]])

In [11]:
np.sort(b)[::-1]

array([[16, 60, 93, 99],
       [38, 74, 96, 97],
       [15, 57, 61, 84],
       [25, 29, 47, 72],
       [12, 20, 22, 81],
       [ 9, 59, 68, 91]])

In [10]:
np.sort(b,axis=0)

array([[ 9, 47, 12, 16],
       [20, 60, 15, 22],
       [29, 61, 25, 59],
       [57, 74, 38, 72],
       [96, 81, 68, 84],
       [99, 91, 93, 97]])

In [12]:
np.sort(b,axis=0)[::-1]

array([[99, 91, 93, 97],
       [96, 81, 68, 84],
       [57, 74, 38, 72],
       [29, 61, 25, 59],
       [20, 60, 15, 22],
       [ 9, 47, 12, 16]])

# np.append()

In [13]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [14]:
np.append(a,200)

array([ 16,  56,  99,  82,  51,  10,  75,  16,  39,  22,  99,  64,  54,
        75,  68, 200])

In [16]:
b

array([[ 9, 91, 68, 59],
       [20, 81, 12, 22],
       [29, 47, 25, 72],
       [57, 61, 15, 84],
       [96, 74, 38, 97],
       [99, 60, 93, 16]])

In [19]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 9., 91., 68., 59.,  1.],
       [20., 81., 12., 22.,  1.],
       [29., 47., 25., 72.,  1.],
       [57., 61., 15., 84.,  1.],
       [96., 74., 38., 97.,  1.],
       [99., 60., 93., 16.,  1.]])

# np.concatenate

In [20]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique()

In [24]:
e = np.array([1,2,3,2,43,6,8,34,5,6,3,2])
np.unique(e)

array([ 1,  2,  3,  5,  6,  8, 34, 43])

# np.expand_dims()

In [25]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [33]:
np.expand_dims(a,axis=0)

array([[16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68]])

In [31]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [34]:
np.expand_dims(a,axis=1)

array([[16],
       [56],
       [99],
       [82],
       [51],
       [10],
       [75],
       [16],
       [39],
       [22],
       [99],
       [64],
       [54],
       [75],
       [68]])

In [32]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where

In [35]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [40]:
np.where(a>50)

(array([ 1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)

In [ ]:
# replace all value > 50 with 0
# np.where(condition , true, false)

In [41]:
np.where(a>50,0,a)

array([16,  0,  0,  0,  0, 10,  0, 16, 39, 22,  0,  0,  0,  0,  0])

In [43]:
np.where(a%2==0,'even','odd')

array(['even', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'even', 'odd', 'even'], dtype='<U4')

# np.argmax

In [44]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [45]:
np.argmax(a) # return index

2

In [46]:
b

array([[ 9, 91, 68, 59],
       [20, 81, 12, 22],
       [29, 47, 25, 72],
       [57, 61, 15, 84],
       [96, 74, 38, 97],
       [99, 60, 93, 16]])

In [47]:
np.argmax(b,axis=1)

array([1, 1, 3, 3, 3, 0], dtype=int64)

# np.argmin()

In [49]:
np.argmin(a)

5

In [53]:
np.argmin(b,axis=1)

array([0, 2, 2, 2, 2, 3], dtype=int64)

# np.cumsum()

In [55]:
b

array([[ 9, 91, 68, 59],
       [20, 81, 12, 22],
       [29, 47, 25, 72],
       [57, 61, 15, 84],
       [96, 74, 38, 97],
       [99, 60, 93, 16]])

In [56]:
np.cumsum(b)

array([   9,  100,  168,  227,  247,  328,  340,  362,  391,  438,  463,
        535,  592,  653,  668,  752,  848,  922,  960, 1057, 1156, 1216,
       1309, 1325])

In [54]:
np.cumsum(b,axis=1)

array([[  9, 100, 168, 227],
       [ 20, 101, 113, 135],
       [ 29,  76, 101, 173],
       [ 57, 118, 133, 217],
       [ 96, 170, 208, 305],
       [ 99, 159, 252, 268]])

# np.cumprod

In [57]:
np.cumprod(a)

array([         16,         896,       88704,     7273728,   370960128,
        -585366016,  -952778240,  1935417344, -1828134912, -1564262400,
        -243154944,  1617952768,  1470103552, -1411383296, -1484783616])

In [58]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

# np.percentile

In [59]:
np.percentile(a,100)

99.0

In [60]:
np.percentile(a,0)

10.0

In [61]:
np.percentile(a,50)

56.0

# np.histogram

In [64]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [63]:
np.histogram(a, bins = 10)

(array([3, 1, 0, 1, 2, 1, 2, 2, 1, 2], dtype=int64),
 array([10. , 18.9, 27.8, 36.7, 45.6, 54.5, 63.4, 72.3, 81.2, 90.1, 99. ]))

# np.corrcoef

In [66]:
salary = np.array([10000,20000,30000,40000,50000,60000,70000])
exp = np.array([1,2,3,4,5,1,2])
np.corrcoef(salary,exp)

array([[1.        , 0.15309311],
       [0.15309311, 1.        ]])

# np.isin

In [67]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [68]:
np.isin(a,5)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [70]:
a[np.isin(a,16)]

array([16, 16])

In [71]:
items=[16,56,33,22]

In [72]:
np.isin(a,items)

array([ True,  True, False, False, False, False, False,  True, False,
        True, False, False, False, False, False])

In [73]:
a[np.isin(a,items)]

array([16, 56, 16, 22])

# np.flip

In [74]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [75]:
np.flip(a)

array([68, 75, 54, 64, 99, 22, 39, 16, 75, 10, 51, 82, 99, 56, 16])

In [76]:
b

array([[ 9, 91, 68, 59],
       [20, 81, 12, 22],
       [29, 47, 25, 72],
       [57, 61, 15, 84],
       [96, 74, 38, 97],
       [99, 60, 93, 16]])

In [77]:
np.flip(b)

array([[16, 93, 60, 99],
       [97, 38, 74, 96],
       [84, 15, 61, 57],
       [72, 25, 47, 29],
       [22, 12, 81, 20],
       [59, 68, 91,  9]])

In [78]:
np.flip(b,axis=1)

array([[59, 68, 91,  9],
       [22, 12, 81, 20],
       [72, 25, 47, 29],
       [84, 15, 61, 57],
       [97, 38, 74, 96],
       [16, 93, 60, 99]])

In [79]:
np.flip(b,axis=0)

array([[99, 60, 93, 16],
       [96, 74, 38, 97],
       [57, 61, 15, 84],
       [29, 47, 25, 72],
       [20, 81, 12, 22],
       [ 9, 91, 68, 59]])

# np.put()

In [80]:
a

array([16, 56, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [81]:
np.put(a,[0,1],[1,10])

In [82]:
a

array([ 1, 10, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

# np.delete()

In [83]:
a

array([ 1, 10, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [84]:
np.delete(a,0)

array([10, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [85]:
np.delete(a,[0,2,4])

array([10, 82, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

# Set Function
- np.union1d
- np.intersect1d
- np.settdiff1d
- np.setxor1d
- np.in1d

In [87]:
m = np.array([1,3,5,7,4,3,6,8,8])
n = np.array([3,2,5,7,3,8,5,3,6])

In [88]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
np.intersect1d(m,n)

array([3, 5, 6, 7, 8])

In [91]:
np.setdiff1d(m,n)

array([1, 4])

In [92]:
np.setdiff1d(n,m)

array([2])

In [93]:
np.setxor1d(m,n)

array([1, 2, 4])

In [95]:
np.in1d(m,1)

array([ True, False, False, False, False, False, False, False, False])

In [96]:
m

array([1, 3, 5, 7, 4, 3, 6, 8, 8])

# np.clip()

In [97]:
a

array([ 1, 10, 99, 82, 51, 10, 75, 16, 39, 22, 99, 64, 54, 75, 68])

In [98]:
np.clip(a,1,75)

array([ 1, 10, 75, 75, 51, 10, 75, 16, 39, 22, 75, 64, 54, 75, 68])

In [99]:
np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])