# Numpy array

In [1]:
import numpy as np

## 1D array

In [2]:
# 1D array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#2D array
b=np.array([[1,3,4],[2,45,6],[2,4,6]])
b

array([[ 1,  3,  4],
       [ 2, 45,  6],
       [ 2,  4,  6]])

In [4]:
#3D array -- also as Tensors
c=np.array([[[1,2,3],[2,4,6]],[[1,3,5],[1,5,7]]])
c

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 3, 5],
        [1, 5, 7]]])

## dtype

In [5]:
# dtype
np.array([1,23,4],dtype=float)

array([ 1., 23.,  4.])

In [6]:
np.array([0,3,4],dtype=bool)

array([False,  True,  True])

In [7]:
np.array([1,34,5],dtype=complex)

array([ 1.+0.j, 34.+0.j,  5.+0.j])

## np.arange

In [8]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2) # with stride

array([1, 3, 5, 7, 9])

## with reshape

In [10]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## np.ones and np.zeros

In [11]:
# np.ones and np.zeros used in neural network and to initialize a array also used
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
 np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.random

In [13]:
# np.random
np.random.random((2,3))

array([[0.42481156, 0.77215568, 0.37070278],
       [0.32845997, 0.47932125, 0.0308242 ]])

## np.linspace

In [14]:
# np.linspace linearly spaced
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [15]:
np.linspace(-10,10,20,dtype=int)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,  10])

## np.identity

In [16]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy attributes

In [17]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
# ndim
a3.ndim

3

In [19]:
a1.ndim

1

In [20]:
a2.ndim

2

In [21]:
# shape
a1.shape

(10,)

In [22]:
a2.shape

(3, 4)

In [103]:
a3.shape

(2, 2, 3)

In [24]:
# size -- tells about no of items
a3.size

8

In [25]:
a1.size

10

In [26]:
a2.size

12

In [27]:
# itemsize
a1.itemsize

4

In [28]:
a2.itemsize

8

In [29]:
a3.itemsize

4

In [30]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

## astype -- Changing datatype to reduce space 32 to 64 bit 

In [31]:
# astype
a3.dtype

dtype('int32')

In [32]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operation

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print('-----------------------------')
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------------------
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Scaler operation

In [34]:
# arithmetic -- any arithmetic ops add,sub,multi,div,modul
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [35]:
# relational -- any relation
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Vector operaton - when in doing operation|s in 2 array

In [36]:
# arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [37]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Function

In [38]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[65., 58., 62.],
       [25.,  4., 49.],
       [ 8., 14., 88.]])

## max/min/sum/prod

In [39]:
np.max(a1)

88.0

In [40]:
np.min(a1)

4.0

In [41]:
np.sum(a1)

373.0

In [42]:
np.prod(a1)

11288333056000.0

In [43]:
# we can get this all by axis also , 0 =column 1= row
np.max(a1,axis = 1)

array([65., 49., 88.])

In [44]:
np.prod(a1,axis=1)

array([233740.,   4900.,   9856.])

In [45]:
np.max(a1,axis=0)

array([65., 58., 88.])

## mean/median/std/var

In [46]:
np.mean(a1)

41.44444444444444

In [47]:
np.median(a1,axis=1)

array([62., 25., 14.])

In [48]:
np.std(a1,axis=0)

array([23.89328125, 23.45681611, 16.21384868])

In [49]:
np.var(a1)

780.0246913580247

# Dot product

In [50]:
a2 = np.arange(12).reshape(3,4)
print(a2)
print('---------------------------------------')
a3 = np.arange(12).reshape(4,3)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [51]:
np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

# Log and exponent

In [52]:
np.log(a1)

array([[4.17438727, 4.06044301, 4.12713439],
       [3.21887582, 1.38629436, 3.8918203 ],
       [2.07944154, 2.63905733, 4.47733681]])

In [53]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# round/floor/ceil

In [54]:
# round -- it will round off to nearest Integer 0.6 -> 1.0
np.round(np.random.random(12))

array([0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1.])

In [55]:
# floor -- it will goes to back integer 0.9 -> 0.
np.floor(np.random.random(12))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
# ceil -- it goes to above integer 0.1 => 1.
np.ceil(np.random.random(12))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Indexing and Slicing

In [57]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a2[1,3]

7

In [59]:
a2[0,1]

1

In [60]:
a3=np.arange(12).reshape(2,2,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [61]:
a3[0,0,2]

2

In [62]:
a3[1,1,2]

11

## slicing

In [63]:
s1=np.round((np.random.random(12))*100)

In [64]:
s1

array([56., 40., 55.,  2.,  5., 44., 78.,  8., 43., 38., 83., 56.])

In [65]:
s1[2:7]

array([55.,  2.,  5., 44., 78.])

In [66]:
s2 = np.arange(12).reshape(3,4)
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
s2[0,:]

array([0, 1, 2, 3])

In [68]:
s2[:,3]

array([ 3,  7, 11])

In [69]:
s2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [70]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
s2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [72]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
s2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [74]:
s2[1,0::3]

array([4, 7])

In [75]:
s2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [76]:
# 3D

In [77]:
s3 = np.arange(27).reshape(3,3,3)
s3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
s3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [79]:
s3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
s3[0,1]

array([3, 4, 5])

In [81]:
s3[1,:,1]

array([10, 13, 16])

In [82]:
s3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
s3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [84]:
s3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [85]:
s1

array([56., 40., 55.,  2.,  5., 44., 78.,  8., 43., 38., 83., 56.])

In [86]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
s3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
#1D
for i in s1:
    print(i)

56.0
40.0
55.0
2.0
5.0
44.0
78.0
8.0
43.0
38.0
83.0
56.0


In [89]:
# 2D
for i in s2:
    print(i)
    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [90]:
#3D
for i in s3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [91]:
for i in np.nditer(s3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [92]:
# reshape
# transpose
# ravel

In [93]:
# transpose
np.transpose(s2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [94]:
s2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
# ravel - conert to 1d
s3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [96]:
# Horizontal stacking
np.hstack((s2,a2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [97]:
s2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
np.vstack((s2,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Splitting

In [100]:
# horizontal stacking
np.hsplit(s2,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [101]:
# Vertical splitting
np.vsplit(s2,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]